#!/bin/bash

pip install pipx
pipx ensurepath
# pipx install ansible
pipx install poetry

poetry install
poetry run ansible-galaxy collection install community.general
poetry run ansible-galaxy collection install ansible.posix
poetry run ansible-playbook base.yml